// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjERDIQUZ3nXSbcIQK4jYpwJf_7q6t5xw',
    appId: '1:413257106131:web:5b8491deddb9cc00784a26',
    messagingSenderId: '413257106131',
    projectId: 'fir-2d178',
    authDomain: 'fir-2d178.firebaseapp.com',
    databaseURL: 'https://fir-2d178-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-2d178.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0q9v_fRJdXTqwx-gk_jt7oQX3CKLnowc',
    appId: '1:413257106131:android:0088ca7ddab71548784a26',
    messagingSenderId: '413257106131',
    projectId: 'fir-2d178',
    databaseURL: 'https://fir-2d178-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-2d178.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC97seLKrMkHwwgWP8ilN6xuUscAHbW3Q4',
    appId: '1:413257106131:ios:1172bb2870217f15784a26',
    messagingSenderId: '413257106131',
    projectId: 'fir-2d178',
    databaseURL: 'https://fir-2d178-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-2d178.appspot.com',
    iosBundleId: 'com.example.ecommerceProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC97seLKrMkHwwgWP8ilN6xuUscAHbW3Q4',
    appId: '1:413257106131:ios:2e75c593d9ead4d3784a26',
    messagingSenderId: '413257106131',
    projectId: 'fir-2d178',
    databaseURL: 'https://fir-2d178-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-2d178.appspot.com',
    iosBundleId: 'com.example.ecommerceProject.RunnerTests',
  );
}
